title: DestinE DataLake Lab
author: DestinE Data Lake Team
logo: https://hda.data.destination-earth.eu/ui/images/destination_earth_logo_W.svg

html:
  home_page_in_navbar: true
  favicon: https://hda.data.destination-earth.eu/ui/images/favicon.svg

execute:
  # To execute notebooks via a Binder instead, replace 'cache' with 'binder'
  execute_notebooks: "off"
  timeout: 3600
  allow_errors: False

parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

#######################################################################################
# Launch button settings
launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: jupyterlab
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://binder-217-71-193-124.nip.io"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  #jupyterhub_url: "https://jupyter.central.data.destination-earth.eu/"  

repository:
  url: https://github.com/destination-earth/DestinE-DataLake-Lab  # The URL to your book's repository
  #path_to_book: "book"  # A path to your book's folder, relative to the repository root.
  branch: notebook-gallery  # Which branch of the repository should be used when creating links

collapse_navbar: true

#######################################################################################
# Advanced and power-user settings
sphinx:
  # A list of extra extensions to load by Sphinx (added to those already used by JB).
  extra_extensions:
    - sphinx_design
    - sphinx.ext.githubpages
    - nbsphinx
  # A list of local extensions to load by sphinx specified by "name: path" items 
  local_extensions:
    notebook_cards: './extensions'
  # sphinx-gallery configuration
  # sphinx_gallery_conf:
  #   # path to your example scripts
  #   examples_dirs:
  #     - './HDA'
  #     - './STACK'
  #     - './HOOK'
  #   # path to where to save gallery generated output
  #   gallery_dirs: ['HDA-gallery', 'STACK-gallery', 'HOOK-gallery']
  #   # specify that examples should be ordered according to filename
  #   within_subsection_order: FileNameSortKey
  config:
    exclude_patterns: ["__pycache__*", "**/.git", ".pixi**", "book/**"]
    html_static_path: ["_stactic"]
    html_css_files: ["custom.css"]
    

