channels:
  - conda-forge
  - defaults
dependencies:
  - "bokeh>=2.4.2,<3"
  - dask-gateway=2023.1.1
  - cloudpickle=2.2.1
  - s3fs=2023.6.0
  - fsspec=2023.6.0
  - xarray=2023.7.0
  - dask=2023.8.0
  - distributed=2023.8.0
  - lz4=4.3.2
  - tornado=6.3.2
  - rioxarray
  - python=3.11.4
  - datacube
  - zarr
  - pip
  - leafmap
  - geopandas
  - pyresample
  - eccodes=2.35.0
  - python-eccodes
  - earthkit-data
  - rioxarray
  - ipywidgets
  - ipyleaflet=0.17.3
  - python-graphviz
  - pip:
      - pystac_client
      - rich
      - odc-stac
      - dedl-stack-client
      - destinelab==0.11
      - polytope-python
      - earthkit-maps
      - earthkit-meteo
      - earthkit-plots
      - earthkit-regrid
      - cf-units
      - git+https://github.com/CS-SI/eodag.git@v3.0.0b2
      - localtileserver
