[project]
authors = ["Christoph Reimer <christoph.reimer@eodc.eu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DestinE-DataLake-Lab"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family="glibc", version="2.26" }

[tasks]

[dependencies]
python = "3.11.*"
jupyter-book = ">=1.0.3,<2"
pydata-sphinx-theme = ">=0.16.0,<0.17"
ghp-import = ">=2.1.0,<3"
nbsphinx = ">=0.9.5,<0.10"
sphinx-gallery = ">=0.18.0,<0.19"
