# This Role allows the 'airflow-worker' ServiceAccount to create PersistentVolumeClaims in the 'airflow' namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: airflow
  name: pvc-creator
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch"]
